/* Generated by Together */

/** created by XPTest for TogetherJ changes to this file will be lost on update. */

package asi.voronoi;

import junit.framework.*;
import junitx.framework.*;
import junit.swingui.*;

/** @stereotype test package */
public class LocalTestPackage implements TestPackage {
    /**
     * main method for running the JUnitX UI.
     * @param   anArgArray    an array of options
     */
    static public void main(String[] anArgArray) {
        junit.swingui.TestRunner.run(LocalTestPackage.class);
    }

    /**
     * creates a suite of test cases.
     * @return  a <code>TestSuite</code>
     */
    static public Test suite() {
        TestSuite suite = new TestSuite("LocalTestPackage test suite");
        suite.addTestSuite(asi.voronoi.test.TestBinaryTree.class);
        suite.addTestSuite(asi.voronoi.test.TestIntervalTree.class);
        suite.addTestSuite(asi.voronoi.test.TestPoint.class);
        return suite;
    }
}
